project:
  type: website
  output-dir: docs

website:
  title: "Lauren Van De Hey"
  body-footer: | 
    ![](/img/banner1.jpg)
  sidebar: false
  navbar:
    right:
      - href: index.qmd
        icon: card-heading
        text: About
      - href: publications.qmd
        icon: journals
        text: Publications & Projects
      - icon: file-earmark-pdf-fill
        text: CV
        href: "https://www.dropbox.com/scl/fi/r630z12h8rzjzil6jk6xb/Van-De-Hey-Lauren_CV_2023.pdf?rlkey=jylon3kwcqbvm8rl8c61nffex&dl=0"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
