---
title: Publications and Projects
toc: false
---
## Under Review:

-   *Multidimensional Constructions of Target Groups and Their Implications: The Case of Immigrant (Il)legality (with Kirill Zhirkov)

## Working Projects:

-   *Just a Little Melancholic, Maybe a Little Blue:* Mental Health as an Emerging Political Identity

    -   Presented at the Annual Midwest Political Science Association Conference 2023, to be presented at American Political Science Association Annual Meeting 2023.

-   *Institutional Trust in the Age of COVID-19: Does low Institutional Trust Lead to Worse Mental Health?*

    -   To be presented at the Political Psychology Pre-Conference of the American Political Science Association Annual Meeting 2023.

-   *(Un)stable Genius? Candidate Depression, Addiction, and Voter Attributes*

    -   Presented at the Annual Political Science Association Conference 2022

-   *Getting Blogged Down: Tracing Illiberal Political thought Through Blogs Using Text Analysis (with Galen Sheely and Samantha Koreman)*

    -   Presented at the Annual Midwest Political Science Association Conference 2023, to be presented at American Political Science Association Annual Meeting 2023.

-   Empirical Studies of Political Obligation: Twenty Years Later (with Samantha Koreman)

    -   Presented at the Annual Midwest Political Science Association Conference 2023
